version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/rails/yukiblog
hooks:
  BeforeInstall:
    - location: /scripts/before-deploy.sh
  # AfterInstall:
  #   - location: Scripts/RunResourceTests.sh
  #     timeout: 180
  ApplicationStart:
    - location: /scripts/app-start.sh
      timeout: 3600