version: 0.1

phases:
  build:
    commands:
      - aws deploy push --region ap-northeast-1 --application-name yukiblog --s3-location s3://yukiblog-codebuild/yukiblog.zip --source ./
artifacts:
  files:
    - '**/*'
  base-directory: ./
  name: yukiblog.zip